# Generated by Django 2.2.1 on 2019-12-02 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('turniket', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='excel',
            old_name='name',
            new_name='action',
        ),
    ]
