# Generated by Django 2.2.1 on 2019-12-09 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('turniket', '0003_auto_20191202_2321'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('excel_name', models.CharField(max_length=50)),
                ('status', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=20)),
                ('came', models.CharField(max_length=10)),
                ('gone', models.CharField(max_length=10)),
                ('early_came', models.IntegerField()),
                ('late_came', models.IntegerField()),
                ('early_gone', models.IntegerField()),
                ('late_gone', models.IntegerField()),
                ('build_exit', models.IntegerField()),
                ('distraction', models.IntegerField()),
                ('overall_ghour', models.IntegerField()),
                ('overall_hour', models.IntegerField()),
                ('staff_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='turniket.Staff')),
            ],
        ),
    ]
