# Generated by Django 2.2.1 on 2019-12-09 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turniket', '0004_log_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='staff_id',
            field=models.IntegerField(),
        ),
    ]
