# Generated by Django 2.2.1 on 2019-12-13 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turniket', '0005_auto_20191209_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='distraction',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='log',
            name='early_came',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='log',
            name='early_gone',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='log',
            name='late_came',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='log',
            name='late_gone',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='log',
            name='overall_ghour',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='log',
            name='overall_hour',
            field=models.CharField(max_length=20),
        ),
    ]
