# Generated by Django 2.2.1 on 2019-12-13 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turniket', '0007_remove_log_staff_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='fullname',
            field=models.CharField(default=' null', max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='log',
            name='came',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='log',
            name='gone',
            field=models.CharField(max_length=20),
        ),
    ]
