# Generated by Django 3.0.1 on 2019-12-29 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turniket', '0008_auto_20191213_1734'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('date', models.CharField(max_length=20)),
                ('hour1', models.CharField(max_length=20)),
                ('hour2', models.CharField(max_length=20)),
                ('reason', models.CharField(max_length=20)),
                ('note', models.CharField(max_length=20)),
            ],
        ),
    ]
