# Generated by Django 3.0.1 on 2019-12-30 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turniket', '0009_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='overall_ghourdec',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='log',
            name='overall_hourdec',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='log',
            name='build_exit',
            field=models.IntegerField(null=True),
        ),
    ]
