# Generated by Django 3.0.1 on 2019-12-30 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turniket', '0011_log_late_camebin'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='permission',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='log',
            name='permissionreason',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
