# Generated by Django 3.0.1 on 2020-01-09 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turniket', '0012_auto_20191229_2328'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shortday',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='log',
            name='graph',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
