# Generated by Django 3.0.1 on 2020-01-31 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turniket', '0013_auto_20200108_2233'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='hour_str',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='log',
            name='modalnum',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
