# Generated by Django 3.0.1 on 2020-02-10 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turniket', '0015_log_modalnumdash'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='late_camedec',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='log',
            name='overtimedec',
            field=models.IntegerField(null=True),
        ),
    ]
