# Generated by Django 3.0.1 on 2020-02-11 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turniket', '0016_auto_20200210_0359'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='early_gonedec',
            field=models.IntegerField(null=True),
        ),
    ]
